version: '3.9'

services:
    db:
      image: mysql:latest
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 'root'
      volumes:
        - ./data/db:/var/lib/mysql

    maildev:
        image: djfarrelly/maildev
        ports:
          - "8002:80"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
          PMA_HOST: db
          UPLOAD_LIMIT: 850M

    web:
        image: nginx:latest
        ports:
          - '80:80'
          - '443:443'
        volumes:
          - ./www/mira5:/var/www/html
          - ./default.conf:/etc/nginx/conf.d/default.conf
          - ./ssl/:/var/www/ssl
        links:
          - php-fpm
    php-fpm:
        build: php82
        volumes:
          - ./www/mira5:/var/www/html
    typesense:
        image: typesense/typesense:0.25.0
        environment:
            TYPESENSE_DATA_DIR: /data
            TYPESENSE_API_KEY: mira
        volumes:
            - /tmp/typesense-server-data:/data
        ports:
            - 8108:8108
    redis:
        image: redis:latest
        ports:
          - '6379:6379'
        volumes: 
          - ./data/cache:/data